theme = "blowfish"
baseURL = "https://nono112002.github.io/"
defaultContentLanguage = "ja"

enableRobotsTXT = true
summaryLength = 0
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
